### ISSUE TITLE
Docker build fails with msgs.Messages undefined (type []*vici.Message has no field or method Messages)

### ISSUE THREAD

**Issue by janisii** [jlti-dev/ipsec_exporter#14]
Hi, 

Docker build fails with `msgs.Messages undefined`.

```
22.06 ./main.go:30:24: msgs.Messages undefined (type []*vici.Message has no field or method Messages)
------
Dockerfile:9
--------------------
   7 |     #	go mod download
   8 |     COPY app /app
   9 | >>> RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  10 |
  11 |     FROM alpine:latest
--------------------
ERROR: failed to solve: process "/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ." did not complete successfully: exit code: 2
```

**Comment by LarsTi** [comment]
Hey there,

sorry i had a lot to do.
I just tried to build it and it seems like i messed up, when i last updated this project.
You can use the previous version `https://hub.docker.com/r/jlti/ipsec_exporter` and it should just work fine.

govici changed its interface and i was not yet able to adapt to the new version.

Kind regards

**Comment by janisii** [comment]
Image from docker hub works. Ty!
