### ISSUE TITLE
the latest version build failed

### ISSUE THREAD

**Issue by fengmikaelson** [jlti-dev/ipsec_exporter#18]
I download the 0.7 version
but i build it failed 
the cmd i use is :

![image](https://github.com/user-attachments/assets/3af05f18-6ba9-4aed-8bb5-eb6871432f67)

**Comment by LarsTi** [comment]
did you try the latest download?
should go to larsti/ipsec_exporter
openvpn_exporter has nothing to do with vici.

try using `ghcr.io/larsti/ipsec_exporter:latest` as docker image.

**Comment by fengmikaelson** [comment]
> did you try the latest download? should go to larsti/ipsec_exporter openvpn_exporter has nothing to do with vici.
> 
> try using `ghcr.io/larsti/ipsec_exporter:latest` as docker image.

finally ， i build a docker container,and then i copy the file from container into my computer, now it works.
but i don't know why i can't build it itself.and i don't know why the errors come out.

**Comment by LarsTi** [comment]
this seems to be related to #14 and the fix merged in #15
